name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "106.162.242.110:443"
UUID = "31c33b8d-5d7e-481c-9b78-921997972c21"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
